thi-ng/umbrella

- packages/rstream/src/subs/transduce.ts
`transduce()` should also unsubscribe from input stream in case of an error. Otherwise we leak the inner subscription.
> fix(rstream): unsubscribe on error in transduce()

- packages/rstream/src/subs/transduce.ts
`transduce()` currently has a subtle bug:
It subscribes to a stream, saves that subscription and unsubscribes on completion. However this fails under certain conditions. A call to transduce() might do the following: 
- transduce() subscribes to the stream
- the stream already has a `last` value and calls the subscription's `next()` method
- if the value is already a reduced value, it will call `sub.unsubscribe()` while `sub` is not yet bound (the binding is still in the _temporal dead zone_)
This PR solves this bug by attaching a then-handler to the promise that unsubscribes the subscription on completion of the stream.
> fix(rstream): Fix potential reference error in transduce()

- packages/rstream/src/subs/timeout.ts
- packages/rstream/test/timeout.ts
This PR adds a `timeout()` subscription. It sends an error down the stream after a configurable amount of time.
> feat(rstream): Add a timeout() subscription

- packages/rstream/src/subs/resolve.ts
This PR fixes the reject handler of the `Resolver.next()` method.
Previously, the expression 
```js
(this.fail || this.error)(e)
``` 
would call the error method of the prototype if no `this.fail` was defined, but without binding `this` to the current object. Thus, the first statement of `Subscription.error()` would fail with the following error:
`TypeError: Cannot set property 'state' of undefined`
> fix(rstream): Fix unbound this in method call expression

- examples/hdom-canvas-clock/src/index.ts
- examples/hdom-canvas-shapes/src/index.ts
- packages/hdom-canvas/README.md
- packages/hdom-canvas/src/index.ts
- packages/hdom/README.md
- packages/hiccup-svg/src/convert.ts
original api uses textBaseline, so use of baseLine is a surprise and
not easy to guess.
> minor(hdom-canvas): baseLine -> baseline

- packages/hdom-canvas/README.md
Documentation for hdom-canvas arc hline and vline calls
@postspectacular I was planning to implement `ellipse` as well, any reasons not to?
> minor(hdom-canvas): add arc, hline, vline to readme

- packages/rstream-gestures/src/index.ts
fixes: https://github.com/thi-ng/umbrella/issues/56
uses getBoundingClientRect() instead of offsetLeft / offsetTop
> fix(rstream-gestures): fix incorrect local position when scrolled

- packages/hdom-canvas/src/index.ts
whoops! last pull request was a bit hasty, didn't actually pass the param to the function call
> fix(hdom-canvas): actually pass maxWidth argument to text function

- packages/cache/src/tlru.ts
- packages/cache/test/tlru.ts
`TLRU.getSet()` behaves like just LRU cache. This method was inhereted from LRU and was not aware of TTL.
> fix(cache): TLRU: expected behavior on getSet()

- packages/webgl/src/fbo.ts
Added check for the number of FBO render targets before actually getting the extension.
For most mobile browsers, [WEBGL_draw_buffers](https://webglstats.com/webgl/extension/WEBGL_draw_buffers) is not supported, but FBOs with single render target are still usable.
> fix(webgl): update check for WEBGL_draw_buffers

- packages/shader-ast/src/builtins.ts
To be a little bit more compliant with GLSL spec `atan` function has two signatures.
See here: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/atan.xhtml
> Add atan signature with two input

- packages/checks/src/exists.ts
This causes `exists` to function as a type guard, preserving the original type of the input.
I have been using this version locally, and I don't think it breaks any builds.  (There is no change to runtime behavior).
> refactor(checks) Stronger typing for `exists`

- packages/api/src/mixins/ienable.ts
- packages/api/src/mixins/inotify.ts
- packages/api/src/mixins/iwatch.ts
This simplifies the mixins code by using [`this` parameters](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters).  It has no effect on runtime, though it does eliminate intermediate variables that were being used to reduce the number of casts.
> refactor(api): Use `this` parameter to avoid casts in mixins.

- packages/transducers-fsm/README.md
Shows required imports and changes `tx.odd` to `isOdd` from `checks`. Got this error without the fix:
```
pred is not a function
```
> Fixes example

- packages/malloc/src/api.ts
- packages/malloc/src/pool.ts
- packages/malloc/test/index.ts
See #138 
Overview:
ArrayBuffer size is now limited to 4GB, due use of uint32 as internal pointers.
We may use BigInt64, but it has other implications.
each block has 8 bytes overhead to save the size of the block, and pointer to the next block.
Mempool pointers variables (end, top, _free, _used) are now getters/setters, that saves the value onto the arraybuffer itself, into a known offset from the `start`
`start` is not saved into the arraybuffer, as its the anchor point we start to read from.
```ts
protected get top(): number {
return this.dataView.getUint32(this.start + POINTER_TOP_OFFSET);
}
protected set top(value: number) {
this.dataView.setUint32(this.start + POINTER_TOP_OFFSET, value);
}
protected get _free(): MemBlock | null {
const freeAddress = …
```
> refactor(malloc): save state inside the ArrayBuffer

- packages/webgl/src/api/texture.ts
Hi, I think there is a missing `TextureFormat` use case for depth texture in WebGL1. By enabling the [`WEBGL_depth_texture`](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture), you can pass `gl.DEPTH_COMPONENT` to both the `internalformat` and `format` arguments of [`gl.texImage2D()`](https://developer.mozilla.org/zh-CN/docs/Web/API/WebGLRenderingContext/texImage2D) as below
```javascript
gl.texImage2D(gl.TEXTURE_2D, 0, gl.DEPTH_COMPONENT, 512, 512, 0, gl.DEPTH_COMPONENT, gl.UNSIGNED_SHORT, null);
```
> WebGL1 depth texture

- packages/hiccup-carbon-icons/test/contact-sheet.ts
> build(hiccup-carbon-icons) Support tests on Windows environments.

- packages/webgl/src/shader.ts
Just found a weird bug probably caused by leaving `VertexAttribArray` enabled after draw.
[Here](https://observablehq.com/d/44928eb79053a0a9) is a minimal reproducible scenario I found, which take quite a weird combination, so I could be missing something here. And [here](https://stackoverflow.com/questions/12427880/is-it-important-to-call-gldisablevertexattribarray) is another relative dicussion.
If that is the case, disabling `VertexAttribArray` in `Shader.unbind` could be   the fix?
> fix(webgl): `disableVertexAttribArray` in `Shader.unbind`

- packages/webgl/src/fbo.ts
Sometime leaving a fbo activated after creation could lead to surprising behavior (e.g. regular draws show nothing), thought that would be a better to close it here.
> fix(webgl): unbind fbo after configure

- packages/ecs/package.json
A beautiful 1 character pull request...
The @thi.ng/ecs package doesn't seem to publish the components folder:
```
Module not found: Error: Can't resolve './components/object-component'
```
Seems a typo was introduced around 0.3.34...  removing the s!
> Fix components folder include for ecs

- packages/checks/src/index.ts
- packages/checks/src/is-prototype-polluted.ts
- packages/paths/src/mutator.ts
- packages/paths/src/path.ts
- packages/paths/test/index.ts
@d3v53c (https://huntr.dev/users/d3v53c) has fixed a potential Prototype Pollution vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | *
Bug Fix | YES
Original Pull Request | https://github.com/418sec/umbrella/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/@thi.ng/paths/1/README.md
@thi.ng/paths is vulnerable to Prototype Pollution. The vulnerability is due to an incomplete fix. mutIn() function does not have fix implemented.
Prototype Pollution refers to the ability to inject properties into existing JavaScript language construct prototypes, such as objects.
JavaScript allows all Object attributes to be altered, including their magical attributes …
> Security Fix for Prototype Pollution - huntr.dev

- packages/atom/README.md
Wasn't passing in parent `Atom` as first param
> doc(atom): fix eager View example

- packages/zipper/src/zipper.ts
Fixed bug resulting in recursion while traversing in a loop in reverse direction. (prev)
Looping through the tree using prev property results in recursion. On checking checking it seems a typo.
> Fixed bug which was resulting in recursion

- packages/geom-accel/src/kd-tree-map.ts
- packages/geom-accel/src/kd-tree-set.ts
- packages/geom-accel/test/kdtree.ts
I was hoping to take advantage of the KdTreeMap component from geom-accel to support lat/long (or long/lat) based indexing and queries, but the current implementation hardcodes the node distance calculation to vectors/distSq so it doesn't properly handle distances that cross the poles or +/-180 longitude. This PR adds the ability to override the distance function used by KdTreeMap or KdTreeSet to use a different vector distance function (such as vector/distHaversineLatLon) as a drop in replacement.
Added some unit tests for KdTreeMap/KdTreeSet to demonstrate that query works as expected with the default behavior, but properly handles nearest point for spherical coordinates if you specify a haversine distance calculation.
> Configurable vector distance function for KdTreeMap and KdTreeSet

- examples/zig-canvas/zig/main.zig
- packages/wasm-api-dom/include/dom.zig
This PR:
- implements #355 for EventListener and RAFListener
- changes reuseOrAddSlot since it was not working with the changes to EventListener and RAFListener
- refactors zig-canvas example to reflect changes to EventListener and RAFListener
> Update EventListener and RAFListener in wasm-api-dom to allow storing a anyopaque pointer

- packages/wasm-api-canvas/package.json
Looks like "files" needs to include the zig/ and generated/ directories to provide all the necesarry sources when adding the wasm-api-canvas package in via `yarn add @thi.ng/wasm-api-canvas`.
> FIX/packages/wasm-api-canvas/package.json: incl. zig/ + generated/

- packages/axidraw/package.json
- yarn.lock
I tried running the example for @thi.ng/axidraw.
It errored because of a missing dependency `@th.ing/date`
That dependency is used on that line: https://github.com/thi-ng/umbrella/blob/develop/packages/axidraw/src/axidraw.ts#L4
This PR is just to add that missing dependency to @thi.ng/axidraw
> fix: add @thi.ng/date dependency to axidraw

- packages/hiccup-css/src/units.ts
Swap use of unsigned shift for OR `0`
Fixes issue #383
Example use case: 
```ts
const MARGIN_PX = -10;
const cmp = div({ style: "margin-left": px(MARGIN) }, "Hi");
```
> fix(hiccup-css): allow negative values for px

- packages/wasm-api/zig/build-v0.11.zig
Due to changes to the zig build system in master, three small changes are needed to support zig v0.11.0-dev.2266+49e33a2f2
> build(wasm-api): update build-v0.11.zig for zig master

- packages/bench/package.json
Very small fix. The bench package file was missed when updating the clean command, and adding the glob argument to the rimraf command. Package would not build on Windows.
> build: update bench pkg file (update clean cmd)

- packages/rdom-canvas/README.md
It pointed to the root /packages but it seems the intent is to have it as /packages/hiccup
> Fix rdom-canvas README hiccup package link

- packages/random-fxhash/src/index.ts
The [latest version](https://github.com/fxhash/fxhash-package/blob/main/packages/project-sdk/dist/fxhash.js) of the fxhash snippet (now called project SDK) no longer exposes a global `fxhash` variable. Instead, we should use `$fx.hash` ([See Usage section in documentation](https://www.fxhash.xyz/doc/artist/project-sdk)).
I added a check to support the new recommended method and kept the old one for backward compatibility.
Once this is merged, I'd be happy to send a PR to update the [tpl-umbrella-fxhash](https://github.com/thi-ng/tpl-umbrella-fxhash) project to use the new SDK (looks to be quite outdated, as the snippet in the index.html does not support fxparams).
> Use hash from global $fx object

- packages/cache/src/lru.ts
- packages/cache/src/tlru.ts
- packages/cache/test/tlru.test.ts
On attempt to add an element bigger than `maxsize`, regardless of the fact that the element isn't actually added to the cache, size of that element is added to `this._size`, blocking addition of any new elements to the cache
> fix(cache): attempt to add element bigger than `maxsize` blocks addition of any new elements to the cache

- packages/geom-api/src/shape.ts
Fixes a build failure in `geom-axidraw`, and looking at the usages of `__samples` it seems like it's intended to be `Partial`.
> fix(geom-api): __samples attribute should be Partial<SamplingOpts>

- packages/sax/src/index.ts
Hey hey, 
Today I tried to use [thi.ng/sax](https://thi.ng/sax) to parse an RSS XML feed, which eventually has CDATA inside some markup tags, e.g.
```xml
<description>
<![CDATA[ News, stories, features and analysis ]]>
</description>
```
Unfortunatelly the CDATA content was missing, I assume it should be parsed as `body` for the given element. Here's a quick example:
```typescript
import * as sax from "@thi.ng/sax";
import * as tx from "@thi.ng/transducers";
const input = [`<a><d>Content</d></a>`,
`<a><d><![CDATA[Content]]></d></a>`];
function process(input: string) {
console.group(`Input: ${input}`);
const doc = tx.transduce(
sax.parse({ entities: true, children: true }),
tx.last(),
input,
);
console.log(doc!.children![0]);
console.groupEnd();
}
tx.transduce(tx.map(process), tx.last(), …
```
> FIX/packages/sax: make sure CDATA content is parsed into 'body'

- packages/vectors/src/cartesian.ts
- packages/vectors/src/polar.ts
I realized that there is a naming mismatch in the text mismatch when looking at the docs for the polar / cartesian conversion fns: https://docs.thi.ng/umbrella/vectors/functions/cartesian.html.
I changed the references in the source code, but still saw the docs using `cartesian(out, a, b?)` as the function signature after generating the docs locally. I ran the following commands to regenerate the docs:
```
yarn clean
yarn build
yarn doc:ae
yarn doc
```
Is there anything else to do? I didn't find anything with `rg -i 'cartesian.*?out.*?a.*?b'`. 
If this is a bug in typedoc I may also go the other way around and rename the function params to `a` and `b`.
> docs: use same parameter names as in doc string
